#
# docker-compose.yml exemple que l'on peut aussi utiliser
# pour debugguer et developper en local
#

version: "3"

services:

  bacon-cache-warmer-demo:
    build: ./image/
    image: bacon-cache-warmer:1.2.0
    container_name: bacon-cache-warmer-demo
    environment:
      BACON_RSS_URL: "https://bacon.abes.fr/rss"
      #BACON_URL_SED_BEFORE_WARM: 's#http://bacon.abes.fr/package2kbart/\([A-Z0-9_-]\+\)#\1#g'
      BACON_URL_SED_BEFORE_WARM: 's#http://bacon.abes.fr/\(.*\)#https://bacon.abes.fr/\1#g'
      BACON_DELAY_BETWEEN_WARM: "2"
      BACON_MAX_URL_TO_WARM: "3"
      BACON_CACHEWARMER_JUST_ONCE: "yes"
      BACON_CACHEWARMER_CRON: "0 3 * * *"
